ruby/catlandia/config/routes.rb
Rails.application.routes.draw do

  root :to => 'cats#index'

  get 'cats/breed' => 'cats#breed'
  get 'cats/origin' => 'cats#origin'

  resources :cats

end

ruby/catlandia/app/models/cat.rb
class Cat < ActiveRecord::Base
end

ruby/catlandia/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: [:show, :edit, :update, :destroy]

  # GET /cats
  # GET /cats.json
  def index
    @cats = Cat.all
  end

  # GET /cats/1
  # GET /cats/1.json
  def show
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
  end

  def breed
    @cats = Cat.all
  end

  def origin
    @cats = Cat.all
  end

  # POST /cats
  # POST /cats.json
  def create
    @cat = Cat.new(cat_params)

    respond_to do |format|
      if @cat.save
        format.html { redirect_to @cat, notice: 'Cat was successfully created.' }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1
  # PATCH/PUT /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to @cat, notice: 'Cat was successfully updated.' }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    @cat.destroy
    respond_to do |format|
      format.html { redirect_to cats_url, notice: 'Cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cat_params
      params.require(:cat).permit(:breed, :origin, :image, :description)
    end
end

ruby/catlandia/app/helpers/cats_helper.rb
module CatsHelper
end

ruby/catlandia/app/views/cats/_form.html.erb
<%= form_for(@cat) do |f| %>
  <% if @cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
      <% @cat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :breed %><br>
    <%= f.text_field :breed %>
  </div>
  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_field :origin %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ruby/catlandia/app/views/cats/breed.html.erb
<nav>
  <ul>
    <li><%= link_to 'Home', cats_path %></li>
    <li><%= link_to 'Add Kitty', new_cat_path %></li>
  </ul>
</nav>

<h1>Kittyz kinds</h1>

<ul class="cats_breed">

    <% @cats.each do |cat| %>

      <li>
        <p><%= link_to cat.breed, cat %></p>
      </li>

    <% end %>

</ul>

ruby/catlandia/app/views/cats/edit.html.erb
<nav>
  <ul>
    <li><%= link_to 'Home', cats_path %></li>
    <li><%= link_to 'Breeds', cats_breed_path %></li>
    <li><%= link_to 'Origin', cats_origin_path %></li>
    <li><%= link_to 'Add Kitty', new_cat_path %></li>
  </ul>
</nav>

<h1>Editing Cat</h1>

<%= render 'form' %>

<%= link_to 'Show', @cat %> |

ruby/catlandia/app/views/cats/index.html.erb
<p id="notice"><%= notice %></p>
<div class="logo">
  <%= image_tag('http://cdn.mysitemyway.com/etc-mysitemyway/icons/legacy-previews/icons/pink-jelly-icons-animals/014197-pink-jelly-icon-animals-animal-cat-print.png') %>
</div>
<nav>
  <ul>
    <li><%= link_to 'Home', cats_path %></li>
    <li><%= link_to 'Breeds', cats_breed_path %></li>
    <li><%= link_to 'Origin', cats_origin_path %></li>
    <li><%= link_to 'Add Kitty', new_cat_path %></li> 
  </ul>
</nav>

<h1>Purrfect Kittiz</h1>

<ul class="cats_table">

    <% @cats.each do |cat| %>
      <li>
        <%= image_tag(cat.image) %>
        <section>
          <p>Breed: <%= link_to cat.breed, cat %></p>
          <p>Origin: <%= cat.origin %></p>
          <p>Description: <%= cat.description %></p>
          <td><%= link_to 'Edit', edit_cat_path(cat) %></td>
          <td><%= link_to 'Destroy', cat, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </section>
      </li>
    <% end %>

</ul>

ruby/catlandia/app/views/cats/new.html.erb
<nav>
  <ul>
    <li><%= link_to 'Home', cats_path %></li>
    <li><%= link_to 'Breeds', cats_breed_path %></li>
    <li><%= link_to 'Origin', cats_origin_path %></li>
    <li><%= link_to 'Add Kitty', new_cat_path %></li>
  </ul>
</nav>

<h1>Yay, add more kittiz!</h1>

<%= render 'form' %>

ruby/catlandia/app/views/cats/origin.html.erb
<nav>
  <ul>
    <li><%= link_to 'Home', cats_path %></li>
    <li><%= link_to 'Add Kitty', new_cat_path %></li>
  </ul>
</nav>

<h1>Kittyz kinds</h1>

<ul class="cats_breed">

    <% @cats.each do |cat| %>

      <li>
        <p><%= link_to cat.origin, cat %></p>
      </li>

    <% end %>

</ul>

ruby/catlandia/app/views/cats/show.html.erb
<nav>
  <ul>
    <li><%= link_to 'Home', cats_path %></li>
    <li><%= link_to 'Breeds', cats_breed_path %></li>
    <li><%= link_to 'Origin', cats_origin_path %></li>
    <li><%= link_to 'Add Kitty', new_cat_path %></li>
  </ul>
</nav>

<p id="notice"><%= notice %></p>

<p>
  <strong>Breed:</strong>
  <%= @cat.breed %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @cat.origin %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag(@cat.image) %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cat.description %>
</p>

<%= link_to 'Edit', edit_cat_path(@cat) %>

ruby/catlandia/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catlandia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="main">
    <%= yield %>
  </div>
  
</body>
</html>